### ISSUE TITLE
`Cannot POST /upload` error

### ISSUE THREAD

**Issue by iafan** [jacopofar/neuraltalk2-web#1]
I'm trying to play around with your web interface, and while it seems to open correctly (the initial static part of the UI), upload always fails with `Cannot POST /upload` message (this is node's internal error message, I guess). I also don't see any handler for `/upload` URLs in your code. Any ideas on where to look at?

**Comment by jacopofar** [comment]
Sorry, that part is not implemented nor documented yet. If you are interested I will implement it in a few days, of course if you have ideas or want to give a try I'm open to pull requests.

For now the only way to upload an image is to temporarily publish it at some URL and then call the /addURL endpoint, it will copy the image immediately and after the captioning will retail the caption for 30 minutes.

**Comment by jacopofar** [comment]
Ok, I just published a new version with the upload, it's still very raw but should allow to upload a file and start the processing.

In 20-30 minutes should be ready on Docker Hub, before that you can copy `index.js`, `helper.js` and install multer using `npm i multer`

EDIT: it's on Docker Hub

**Comment by iafan** [comment]
Yeah, it does upload now. The result is displayed only in the console, not in the web UI, but that's more than enough for quick testing.

**Comment by jacopofar** [comment]
Yes, I didn't add a code to show the result back yet

**Comment by iafan** [comment]
Thanks, Jacopo. I guess you can close the issue.

**Comment by jacopofar** [comment]
Perfect, I'm glad it worked

**Comment by dannybess** [comment]
Hi, 

I'm getting a Return Code 1 error; any ideas on how to fix this?
