### ISSUE TITLE
Failure without return code

### ISSUE THREAD

**Issue by renehagen** [jacopofar/neuraltalk2-web#2]
I run the Docker container on a Synology Diskstation. When I try to get the caption I get {"error":"caption not found, it is expired or yet to be processed"}. The status reports {"timestamp":"2016-01-05T21:25:37.270Z","status":"failure","retCode":null}.

The log shows:
 Application started on port 5000
trying to add the URL https://upload.wikimedia.org/wikipedia/commons/8/85/Garden_bench_001.jpg...
{ path: '/tmp/a2dd4e00-b3f5-11e5-8341-8dcbffd2c245.jpg',
  sha256sum: '5421c617efb140e0c4967051838dc6d6b4894444b29c0bbc649399fee0b0f5ef' }
moved file 0 of 1
neuraltalk2 process exited with code null
 +++ return code from neuraltalk2: null

Same with the webinterface also with other images.

Any Idea what is going wrong here?

**Comment by jacopofar** [comment]
That's strange, even in case of failure the process should exit with a number.

Can you check whether the program works when launched from bash inside the container?

**Comment by renehagen** [comment]
This gives the same result. See attached screenshot.

Met vriendelijke groet,

René Hagen
Tel. 06-24551336

**Comment by renehagen** [comment]
The screenshot is not attached by the email reply it seems. Here it is again

![synology diskstation diskstation](https://cloud.githubusercontent.com/assets/11347255/12169815/c58254ea-b53b-11e5-91fc-4a2fccbda870.png)

**Comment by jacopofar** [comment]
Sorry, I meant running neuraltalk from inside the container. Something like:

```
docker run -it --name neuraltalk2-web -v /home/myuser/:/mounted jacopofar/neuraltalk2-web:latest bash
```

to open a shell inside it, and then:

```
th eval.lua -model /mounted/neuraltalk2models/model_id1-501-1448236541.t7_cpu.t7 -image_folder /mounted/Desktop/ -gpuid -1
```

to perform the classification.

**Comment by renehagen** [comment]
I know very little of linux. So I cannot do much more then entering your commands. I managed to get a shell running inside the container but I get 

root@ea85c37fb:/# th /eval.lua -model /mounted/model/model_id1-501-1448236541.t7_cpu.t7 -image_folder /mounted/ -gpuid -1
/root/torch/install/bin/luajit: cannot open /eval.lua: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by jacopofar** [comment]
You have to `cd` into the directory containing neuraltalk2, with `cd /neuraltalk2`, then to be sure using the `ls` command you will see the `eval.lua` file.

Also consider that the command will be different depending on the paths containing the images and the model file, ensure that you see the images with `ls /mounted` and the model with `ls /mounted/model/model_id1-501-1448236541.t7_cpu.t7`

**Comment by renehagen** [comment]
The eval returned an 'illegal instruction' message

```
DiskStation> docker run -it --name neuraltalk2-web -v /volume1/Rene/:/mounted jacopofar/neuraltalk2-web:latest bash
root@1fb30b02c552:/webapp# cd /
root@1fb30b02c552:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  mounted  neuraltalk2  opt  proc  root  run  sbin  srv  sys  tmp  torch-hdf5  usr  var  webapp
root@1fb30b02c552:/# cd neuraltalk2
root@1fb30b02c552:/neuraltalk2# ls
README.md  coco-caption                       cv        misc       test_language_model.lua  videocaptioning.lua
coco       convert_checkpoint_gpu_to_cpu.lua  eval.lua  prepro.py  train.lua                vis
root@1fb30b02c552:/neuraltalk2# th eval.lua -model /mounted/model/model_id1-501-1448236541.t7_cpu.t7 -image_folder /mounted/Images/ -gpuid -1
Illegal instruction
root@1fb30b02c552:/neuraltalk2# ls /mounted/images
DSC_0203.JPG
root@1fb30b02c552:/neuraltalk2# ls /mounted/model
model_id1-501-1448236541.t7_cpu.t7
root@1fb30b02c552:/neuraltalk2# th eval.lua -model /mounted/model/model_id1-501-1448236541.t7_cpu.t7 -image_folder /mounted/images/ -gpuid -1
Illegal instruction
```

**Comment by jacopofar** [comment]
I suspect you are running with not enough memory. Use `free -h`to be sure how much RAM is available to the container, but in general you'll need at least 2-3 GBs to run the software.

**Comment by renehagen** [comment]
That's a showstopper on my Synology NAS. I cannot give it more then 1Gb.

I will setup a VM on a different machine and give that a try.

Thanks for your support.

**Comment by jacopofar** [comment]
You welcome!

**Comment by richterd** [comment]
Hi, I am experiencing a similar issue, where it returns:

```
...
DataLoaderRaw found 12 images
constructing clones inside the Language Model
Illegal instruction (core dumped)
```

`free -h` in container says that there are 3.7G of Mem and 2.1G of them are free. Could this still be a "not enough memory"-issue? 

Best regards,
Daniel

**Comment by jacopofar** [comment]
I guess so, 2.1 GB isn't a lot of RAM for this. Have you tried to process the images one at time?
I suspect it tries to hold them in RAM, and in case of high-resolution images could be a problem. Also it could be one of them is corrupted.

**Comment by richterd** [comment]
Wow, thanks for the superfast reply. I now installed the setup on a MacBook where it works fine. The interesting point is, that it works, although the docker container on the MacBook is per default limited to 2 cpus and 2GB memory...
