### ISSUE TITLE
Failure, Ret Code 1

### ISSUE THREAD

**Issue by dannybess** [jacopofar/neuraltalk2-web#4]
Hi, 

Running the provided code, I am unable to actually process an image.
I am getting this error:

```
 +++ return code from neuraltalk2: 1
uploaded new file: /tmp/306100ac5f3c148264270d1336de2c9d
{ path: '/tmp/b98a2c00-eb1c-11e5-9095-052987811b61.jpg',
  sha256sum: 'ab71ff472ca16f51206feb30f188a30c39122908e9896d74d363c961ba2688c9' }
moved file 0 of 1
stderr: tput: 
stderr: No value for $TERM and no -T specified
stderr: 

stderr: /root/torch/install/bin/luajit
stderr: :
stderr:  
stderr: /root/torch/install/share/lua/5.1/torch/File.lua:268: unknown Torch class <torch.CudaTensor>
stack traceback:
    [C]: in function 'error'
    /root/torch/install/share/lua/5.1/torch/File.lua:268: in function 'readObject'
    /root/torch/install/share/lua/5.1/torch/File.lua:294: in function 'readObject'
    /root/torch/install/share/lua/5.1/torch/File.lua:278: in function 'readObject'
    /root/torch/install/share/lua/5.1/torch/File.lua:294: in function 'readObject'
    /root/torch/install/share/lua/5.1/torch/File.lua:294: in function 'readObject'
    /root/torch/install/share/lua/5.1/torch/File.lua:325: in function 'load'
    eval.lua:69: in main chunk
    [C]: in function 'dofile'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
stderr: 

neuraltalk2 process exited with code 1
 +++ return code from neuraltalk2: 1
```

**Comment by jacopofar** [comment]
Are you sure the model mounted is the one for CPUs and not the GPUs one ? That `CudaTensor`seems related to CUDA, which this build does not support (but

Additionally, how much RAM is available to that container (you can use `free -h` if needed)?

Cheers!

**Comment by dannybess** [comment]
Hey, thanks for the reply.

-free h solved the problem for me, thanks! On another quck note, I noticed that the rocker image is capable of processing multiple images at the same time. Does it process them concurrently, or does it queue them up?

Thanks!

**Comment by jacopofar** [comment]
Images are queued. The Lua application performing the actual captioning reads a folder and processes them together, the web wrapper simply calculates the SHA of the images, moves them in that folder and run the software, reading the results afterwards.

On a side note, the process is way faster in batch, on my computer it takes about 10 seconds to load the model and then needs 1-2 seconds per image. The processing is still sequential, but if the folder has more than 1 image the total time is lower than processing them in different iterations.

**Comment by dannybess** [comment]
Is there anyway to preload the model?

**Comment by dannybess** [comment]
Also, @jacopofar , how would one go about getting more accurate results? I have tried finding a different model file, but have so far been unsuccessful in doing so.

**Comment by jacopofar** [comment]
You can see the [page of the project](https://github.com/karpathy/neuraltalk2) which has a section dedicated to training, but consider the time needed to train such a model is likely to be huge.

I don't see a way to _preload_ the model if not changing the Lua code of the program. Placing the captioning part in an infinite loop after the model loading could work, but the web interface waits for the process to exit afterwards and would never detect the new captions.
